In [1]:
import pandas as pd

df = pd.read_csv('data/iris.csv')
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [2]:
print(df.head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [3]:
print(df.columns)

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')


In [4]:
print(df.shape)

(150, 5)


In [5]:
print(df.index)

RangeIndex(start=0, stop=150, step=1)


In [6]:
print(df.iloc[1])

sepal_length       4.9
sepal_width        3.0
petal_length       1.4
petal_width        0.2
species         setosa
Name: 1, dtype: object


In [7]:
print(df.iloc[1,1])

3.0


In [8]:
print(df.dtypes)

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object


In [11]:
X = df[["sepal_length","sepal_width","petal_length","petal_width"]]
y = df[["species"]]
print(type(X))
print(type(y))
print(X.shape)
print(y.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
(150, 4)
(150, 1)


In [12]:
df2 = df.copy()

df2.iloc[1,1] = 100
print(df2.iloc[1,1])
print(df.iloc[1,1])

100.0
3.0


In [13]:
# Quesion 4
from sklearn.metrics import confusion_matrix
actual = [0, 1, 0, 1]
predicted = [1, 1, 1, 0]
cm = confusion_matrix(actual, predicted)
print(type(cm))
print(" ", "0 ", "1 ", "P ")
print(0, "TN", "FP")
print(1, "FN", "TP")
print("A")
print()
print("confusion matrix")
print(cm)

<class 'numpy.ndarray'>
  0  1  P 
0 TN FP
1 FN TP
A

confusion matrix
[[0 2]
 [1 1]]


In [14]:
from sklearn.metrics import confusion_matrix
actual = ['B', 'M', 'B', 'M']
predicted = ['M', 'M', 'M', 'B']

cm = confusion_matrix(actual, predicted)
print(" ", "B ", "M ", "P ")
print("B", "TN", "FP")
print("M", "FN", "TP")
print("A")
print()
print("CM", cm)
print()

  B  M  P 
B TN FP
M FN TP
A

CM [[0 2]
 [1 1]]



In [18]:
from sklearn.metrics import confusion_matrix
actual = ['W', 'M', 'W', 'M']
predicted = ['M', 'M', 'M', 'W']

cm = confusion_matrix(actual, predicted,
labels=["M", "W"])
print(" ", "W ", "M ", "P ")
print("W ", "TN", "FP")
print("M ", "FN", "TP")
print("A")
print()
print("CM", cm)

  W  M  P 
W  TN FP
M  FN TP
A

CM [[1 1]
 [2 0]]


In [19]:
from sklearn.metrics import confusion_matrix

actual = ["cat", "ant", "cat", "cat", "ant", "bird"]
predicted = ["ant", "ant", "cat", "cat", "ant", "cat"]
cm = confusion_matrix(actual, predicted)
print(cm)
cm = confusion_matrix(actual, predicted,
labels=["ant", "cat", "bird"])
print(cm)

[[2 0 0]
 [0 0 1]
 [1 0 2]]
[[2 0 0]
 [1 2 0]
 [0 1 0]]


In [21]:
#Question 5
from sklearn.datasets import load_iris
import numpy as np
iris = load_iris()
print(type(iris))
print(iris.feature_names)
print(iris.target_names)


<class 'sklearn.utils.Bunch'>
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [22]:
X = iris.data
print("X.shape", X.shape)
y = iris.target
print("y.shape", y.shape)
print(y)
print(iris.DESCR)

X.shape (150, 4)
y.shape (150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ======

In [23]:
# Question 6
from sklearn.preprocessing import OneHotEncoder
x = iris.target
print(x.shape)
print(x)
# x needs to be a 2d object
x = x.reshape(-1,1)
print(x.shape)
enc = OneHotEncoder()
enc.fit(x)
print(type(enc.transform(x)))
x_encoded = enc.transform(x).toarray()
print(x_encoded)

(150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
(150, 1)
<class 'scipy.sparse.csr.csr_matrix'>
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.