In [3]:
import pandas as pd

import numpy as np

from sklearn.metrics import confusion_matrix

In [6]:
one_d = np.array([12, 3, 6, 14])
two_d = np.array([ [1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12] ])
three_d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[21, 22, 23, 24], [25, 26, 27, 28], [29, 30, 31, 32]]])

print(one_d[3:4])
print(two_d[1:5])
print(three_d[1:3:4])

[14]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[[21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]]


In [12]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
b = arr.reshape(2, -2)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [13]:
df = pd.read_csv('data/iris.csv')
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [14]:
print(df.head())
print(df.columns)
print(df.shape)
print(df.index)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')
(150, 5)
RangeIndex(start=0, stop=150, step=1)
