In [34]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn import neighbors
df = pd.read_csv('data/wbcd.csv')
print(df.columns)
print(df.diagnosis.value_counts())
# print(df.head())
# print(df.area_mean.describe())
print('Mean of area_mean', df.area_mean.mean())
print('Mean of radius_mean', df.radius_mean.mean())
print('Mean of smoothness_mean', df.smoothness_mean.mean())
X = df.drop(['id', 'diagnosis'], axis='columns')
y = df.diagnosis

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'points_mean', 'symmetry_mean', 'dimension_mean', 'radius_se',
       'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'points_se', 'symmetry_se',
       'dimension_se', 'radius_worst', 'texture_worst', 'perimeter_worst',
       'area_worst', 'smoothness_worst', 'compactness_worst',
       'concavity_worst', 'points_worst', 'symmetry_worst', 'dimension_worst'],
      dtype='object')
B    357
M    212
Name: diagnosis, dtype: int64
Mean of area_mean 654.8891036906854
Mean of radius_mean 14.127291739894558
Mean of smoothness_mean 0.09636028119507911


In [35]:
X = df.drop(['id', 'diagnosis'], axis='columns')
y = df.diagnosis
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)
clf = KNeighborsClassifier()
clf.fit(X_train, y_train)

KNeighborsClassifier()

In [36]:
print('Accuracy', clf.score(X_test, y_test))
yPredict = clf.predict(X_test)
cm = confusion_matrix(y_test, yPredict, labels=['B','M'])
tn, fp, fn, tp = cm.ravel()
print(cm)
print(tn, fp, fn, tp)
print( (tn + tp) / (tn + tp + fn + fp) )

Accuracy 0.9473684210526315
[[72  0]
 [ 6 36]]
72 0 6 36
0.9473684210526315


In [37]:
##Question 2
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
clf = KNeighborsClassifier()
clf.fit(X_train, y_train)

KNeighborsClassifier()

In [38]:
print('Accuracy', clf.score(X_test, y_test))
yPredict = clf.predict(X_test)
cm = confusion_matrix(y_test, yPredict, labels=['B','M'])
tn, fp, fn, tp = cm.ravel()
print(cm)
print(tn, fp, fn, tp)
print( (tn + tp) / (tn + tp + fn + fp) )

Accuracy 1.0
[[72  0]
 [ 0 42]]
72 0 0 42
1.0


In [39]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
clf = KNeighborsClassifier()
clf.fit(X_train, y_train)

KNeighborsClassifier()

In [40]:
print('Accuracy of k', clf.score(X_test, y_test))
yPredict = clf.predict(X_test)
cm = confusion_matrix(y_test, yPredict, labels=['B','M'])
tn, fp, fn, tp = cm.ravel()
print(cm)
print(tn, fp, fn, tp)
print( (tn + tp) / (tn + tp + fn + fp) )

Accuracy of k 0.9824561403508771
[[71  1]
 [ 1 41]]
71 1 1 41
0.9824561403508771


In [43]:
#Question 3

training_accuracy = []
test_accuracy = []
# try n_neighbors from 1 to 10
neighbours = range(1, 11)
for k in neighbours:
 # build the model
 clf = neighbors.KNeighborsClassifier(n_neighbors=k)
 clf.fit(X_train, y_train)
 print("k nearest neighbours value of ", k)
 # record training set accuracy
 training_accuracy.append(clf.score(X_train, y_train))
 print("Training set accuracy: ", clf.score(X_train, y_train))
 # record generalization accuracy
 test_accuracy.append(clf.score(X_test, y_test))
 print("Test set accuracy: ", clf.score(X_test, y_test))

k nearest neighbours value of  1
Training set accuracy:  1.0
Test set accuracy:  0.956140350877193
k nearest neighbours value of  2
Training set accuracy:  0.967032967032967
Test set accuracy:  0.956140350877193
k nearest neighbours value of  3
Training set accuracy:  0.9736263736263736
Test set accuracy:  0.9824561403508771
k nearest neighbours value of  4
Training set accuracy:  0.9648351648351648
Test set accuracy:  0.956140350877193
k nearest neighbours value of  5
Training set accuracy:  0.9648351648351648
Test set accuracy:  0.9824561403508771
k nearest neighbours value of  6
Training set accuracy:  0.9582417582417583
Test set accuracy:  0.9649122807017544
k nearest neighbours value of  7
Training set accuracy:  0.9626373626373627
Test set accuracy:  0.9912280701754386
k nearest neighbours value of  8
Training set accuracy:  0.9604395604395605
Test set accuracy:  0.956140350877193
k nearest neighbours value of  9
Training set accuracy:  0.9604395604395605
Test set accuracy:  0.97